### ISSUE TITLE
Criteria for not polished price alert

### ISSUE THREAD

**Issue by op1ekun** [op1ekun/PolishOurPrices#6]
The initial proposal is to flag more than 5% price deviation, but not less then 1PLN (to avoid chasing pennies).

**Comment by janjag** [comment]
5% in relation to EUR, USD or NOK? Also this is a good place to select currencies for comparison.

**Comment by SimplexPL** [comment]
I would say compared to EUR, as we are in EU. NOK is an outlier, and Norway is not in EU.

**Comment by op1ekun** [comment]
Cool so the main one is EUR, and the rest is just the icing on the cake :)

**Comment by op1ekun** [comment]
As it stands for now the criteria are as follows:
- price diff at least 5%,
- price diff at least 5PLN,
- at least 20 user reviews.
